### ISSUE TITLE
Fix the /Abstract: language about what the spec defines

### ISSUE THREAD

**Issue by webb** [NIEM/MPD-Spec#15]
Does it really define MPDs that conform to NIEM 4? Or just defines MPDs that support NIEM 4-conformant content? Leave the conformance spec to define what conforms to NIEM 4 (which is a bigger umbrella than an MPD)

**Comment by cchipman6** [comment]
Fixed the /Abstract language about what the spec defines; removed "conformance" wording. now reads rules for building a NIEM IEPD.
