### ISSUE TITLE
Replace references to NIEM MPD Toolkit with references to GitHub resources

### ISSUE THREAD

**Issue by webb** [NIEM/MPD-Spec#20]
Current doc references catalog-validating schemas within the NIEM MPD Toolkit, which is being stood down; reference schemas as part of the MPD distribution on github and reference.niem.
The doc also references the COT IEPD as being part of the toolkit. Stand it up as its own repo.

**Comment by cchipman6** [comment]
Replaced references to NIEM MPD Toolkit with references to NIEM Template IEPD repository.  Change is confirmed.
