### ISSUE TITLE
"Examples of valid MPD URIs" are bad

### ISSUE THREAD

**Issue by webb** [NIEM/MPD-Spec#23]
People shouldn't build IEPDs with identifiers that belong to other people. Located [here](https://reference.niem.gov/niem/specification/model-package-description/3.0.1/model-package-description-3.0.1.html#section_5.2.4.1)

**Comment by cchipman6** [comment]
Replaced "Examples of valid IEPD URIs" with URIs that do not include identifiers that belong to other people. Change is verified.
