### ISSUE TITLE
Update Appendices

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/MPD-Spec#27]
Transferring MPD spec issue from https://github.com/NIEM/NIEM.github.io/issues/87...

Update all appendices in the current MPD (https://reference.niem.gov/niem/specification/model-package-description/3.0.1/model-package-description-3.0.1.html) to reflect the current version of NIEM (4.1).

**Comment by cchipman6** [comment]
Need to update NIEM spec versions/namespace URLs in:
- appendix a. iepd-catalog.xsd;
- appendix b. example IEPD catalog document for Cursor on Target;
- appendix c. niem conformance assertion graphic;
- appendix g. references

**Comment by cchipman6** [comment]
The version number was removed from the NIEM specification references in Appendix G; related to issue 29.

**Comment by TomCarlson-NTAC** [comment]
Updated to NIEM 5.0 for the 5.0 release by 28b04804177512ae96645e1e1de132c6974288f9.
