### ISSUE TITLE
Update "NIEM v4.0" text in Abstract

### ISSUE THREAD

**Issue by webb** [NIEM/MPD-Spec#29]
Update the Abstract text about defining IEPDs for NIEM v4.0; this is for any IEPDs conforming to the spec, focusing on satisfying using anything based on v4.

Ensure that an IEPD can conform to this specification, while using other versions of NIEM. There shouldn't be anything in here that requires the use of a specific version of NIEM. This will get tricky when dealing with NDR conformance targets (e.g., reference schemas), which are pegged to a specific NDR.

**Comment by cchipman6** [comment]
1. Removed version numbers from the NIEM specifications references. 2. Added instructions to refer to the current version where applicable. 3. Deleted text from Reference Schema Documents and Extension Schema Document definitions requiring conformance to a specific NDR version.
