### ISSUE TITLE
Will there be a json-ld context published for NIEM 5?

### ISSUE THREAD

**Issue by leilatite** [NIEM/MPD-Spec#51]
Hello,
We're planning to document all of our external interfaces for our new Jail Management System by publishing IEPDs. We plan to use json-ld wherever possible. I see that there were json-ld contexts published for NIEM 4 and NIEM 4.1. Will there be anything published for NIEM 5? Is the direction for json support in NIEM still consistent with what is published on [NIEM and JSON](http://niem.github.io/json/), or are things moving in a different direction?
Thanks,
Leila

**Comment by TomCarlson-NTAC** [comment]
The JSON-LD context for NIEM 5.0 is part of the [release download package](http://niem.github.io/niem-releases/5.0/), specifically `/NIEM-Releases-niem-5.0/json-ld/context.json`.

There is a 5.0 version of the JSON specification that should be in beta soon. It adds some information and techniques, but I don't think it invalidates any of the existing guidance.
