### ISSUE TITLE
Update the MPD catalog schema to be based on NIEM v4 instead of v3

### ISSUE THREAD

**Issue by webb** [NIEM/MPD-Spec#6]
We can update the MPD catalog format to be based on NIEM v4 instead of v3.
Do we want to do this? A change to the MPD catalog, namespace, schema, etc.? Or we can leave all that alone, and just update references to NDR & conformance targets.

**Comment by webb** [comment]
Via email, sense of the NTAC is to update to v4.

**Comment by krishnaVamsy** [comment]
I believe Option 2 would give flexibility for future updates.

**Comment by TomCarlson-NTAC** [comment]
Updated to NIEM 5.0 by 28b04804177512ae96645e1e1de132c6974288f9.
